[project]
name="rag-system"
description="Rag retrieval ingestion"
version="1.0.0"
requires-python=">=3.13"
dependencies = [
    "datasets>=4.8.5",
    "deepeval>=3.9.9",
    "fastapi>=0.136.1",
    "httpx>=0.28.1",
    "litellm>=1.83.0",
    "numpy>=2.4.4",
    "opensearch-py[async]>=3.2.0",
    "pydantic>=2.13.3",
    "pydantic-settings>=2.14.0",
    "pypdf>=6.10.2",
    "ragas>=0.4.3",
    "uvicorn>=0.46.0",
]

[tool.pytest.ini_options]
pythonpath = ["."]
testpaths = ["tests"]
